export const insulte = [
    'le fils de pute',
    'le sociapathe pervers narcissique',
    'le gros pd',
    'l\'obèse',
    'la femme',
    'la pute',
    'la salope',
    'le suceur de daron',
    'le connard',
    'le chien',
    'l\'angloutisseur de pénis',
    'le pénis',
    'le vagin',
    'la bite',
    'le yuumi enjoyer',
    'aka nicolas fisher',
    'le caca',
    'le prout',
    'la diarrhée',
    'la couille gauche',
    'la tumeur',
    'paokdpijaoigrnpinergedazreag',
    'le sperme',
    'le random',
    'le fromage de nombril',
    'la poubelle humaine',
    'le sac à poubelle cosplay',
    'le pet mouillé',
    'la trace de pneu dans le pantalon',
    'le monkey',
    'le singe',
    'l\'animal',
    'le tiroir à pisse',
    'le pipi',
    'les toilettes humaines',
    'se branle actuellement',
    'est entrain de chier sa mère',
    'baise sa mère',
    'le raciste (probablement)',
    'le neonazi irl (probablement)',
    '+ ratio',
    'le weeb',
    'la crotte',
    'la crotte de nez',
    'est un cafaaaard',
    'le rocher',
    'le légume',
    'la banane',
    'la plante verte',
    'le phacochère',
    'le sniffer de pet',
    'l\'enculeur de mouches',
    'l\'aspirateur a foutre',
    'le gay irl',
    'le mec qui CC en aram',
    'la cave a sperme',
    'la cuve a foutre',
    'la trousse à bites',
]
