export const insulte = [
    'le fils de pute',
    'le sociapath pervers narcissique',
    'le gros pd',
    'l\'obèse',
    'la femme',
    'la pute',
    'la salope',
    'le suceur de daron',
    'le connard',
    'le chien',
    'l\'angloutisseur de pénis',
    'le pénis',
    'le vagin',
    'la bite',
    'le yuumi enjoyer',
    'aka nicolas fisher',
    'le caca',
    'le prout',
    'la diarrhée',
    'la couille gauche',
    'la tumeur',
    'paokdpijaoigrnpinergedazreag',
    'le sperme',
    'le random',
    'le fromage de nombril',
    'la poubelle humaine',
    'le sac à poubelle cosplay',
    'le pet mouillé',
    'la trace de pneu dans le pantalon',
    'le monkey',
    'le singe',
    'l\'animal',
    'le tiroir à pisse',
    'le pipi',
    'les toilettes humaines',
    'se branle actuellement',
    'est entrain de chier sa mère',
    'baise sa mère'
]